name: esnuel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - rdkit=2023.03.2
  - numpy=1.25.2
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - threadpoolctl=3.2.0
  - ipython=8.14.0
  - optuna=3.2.0
  - tqdm=4.65.0
  - lightgbm=4.0.0
  - ase=3.22.1
  - submitit=1.2.1
  - openbabel=3.1.1
  - requests=2.31.0
  - py3dmol
  - ipykernel
  - flask=2.3.2
  - sqlalchemy=2.0.19
  - pip:
    - flask-sqlalchemy==3.0.5
    - wtforms==3.0.1
