name: esnuel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.1
  - rdkit=2022.09.1
  - numpy=1.21.4
  - scikit-learn=1.0.1
  - pandas=1.3.4
  - threadpoolctl=3.0.0
  - ipython=7.29.0
  - optuna=2.5.0
  - tqdm=4.62.3
  - lightgbm=3.1.1
  - ase=3.22.1
  - submitit=1.2.1
  - openbabel=3.1.1
  - requests=2.27.1
  - py3dmol
  - ipykernel
